<a href="https://colab.research.google.com/github/Burkifa23/kwizeramugwaneza_frank_lab0/blob/master/colab_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1 NumPy Fundamentals
**Creating Arrays**


In [1]:
import numpy as np

# Creating arrays
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.zeros((3, 4))          # 3x4 array of zeros
arr3 = np.ones((2, 3))           # 2x3 array of ones
arr4 = np.random.randn(3, 3)     # 3x3 random normal
arr5 = np.arange(0, 10, 2)       # [0, 2, 4, 6, 8]
arr6 = np.linspace(0, 1, 5)      # 5 evenly spaced values

print(f"Shape of arr2: {arr2.shape}")
print(f"Dimensions: {arr2.ndim}")
print(f"Data type: {arr3.dtype}")

Shape of arr2: (3, 4)
Dimensions: 2
Data type: float64


**Array Indexing and Slicing**

In [2]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

print(f"First element: {arr[0, 0]}")
print(f"Second column: {arr[:, 1]}")
print(f"Rows 1-2, cols 2-3: \n{arr[1:3, 2:4]}")
print(f"Boolean indexing: {arr[arr > 5]}")

First element: 1
Second column: [ 2  6 10]
Rows 1-2, cols 2-3: 
[[ 7  8]
 [11 12]]
Boolean indexing: [ 6  7  8  9 10 11 12]


**Broadcasting**

Broadcasting allows operations between arrays of different shapes:


In [4]:
# Broadcasting example
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
vector = np.array([10, 20, 30])

# Broadcasting adds vector to each row
result = matrix + vector
print(result)
# [[11, 22, 33],
#  [14, 25, 36],
#  [17, 28, 39]]

# Normalization using broadcasting
data = np.random.randn(100, 5)
normalized = (data - data.mean(axis=0)) / data.std(axis=0)
print(normalized)

[[11 22 33]
 [14 25 36]
 [17 28 39]]
[[-0.13145054  0.13602324 -1.43262131  0.29963112  0.8446614 ]
 [-0.25886813 -0.21671079 -0.13907951 -0.11217152 -1.37814691]
 [ 0.52792762  0.28500974 -1.4463961  -0.05483685  1.27198312]
 [-0.24097549  0.14745223 -0.54926617  1.13229388  0.44000611]
 [ 0.11806179 -1.11894709 -0.18998478  1.27449019 -0.55240887]
 [-1.82982704 -1.91104444 -0.77230872 -0.25938356 -0.77191799]
 [-1.16731586 -1.12333008 -0.71358789  0.20448081 -0.11107787]
 [-1.02631898  0.09393575  0.66291711 -1.4115422  -0.79871605]
 [ 0.81215399 -0.77112598  0.67709576  0.8398859   0.06618859]
 [ 1.6158431   0.50938873 -0.98830449 -0.19179784  0.15675728]
 [-0.24489883 -1.2090685  -0.43136863  0.4161097   0.70732525]
 [ 0.51420695  2.14409456 -0.67915646  1.77761547  1.83871804]
 [ 0.50799795  0.4537077  -0.14806939  1.89331457  0.2424818 ]
 [-1.93890612  0.1710275  -1.09386661 -1.05454577  1.36134133]
 [-0.96206706 -0.35224831  0.73932185 -0.55349157 -0.06240462]
 [ 0.39874584  1.3

**Matrix Operations**


In [6]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Matrix multiplication
C = A @ B  # or np.matmul(A, B)

# Element-wise multiplication
D = A * B

# Transpose
A_T = A.T

# Inverse (requires square, non-singular matrix)
A_inv = np.linalg.inv(A)

# Determinant
det_A = np.linalg.det(A)

# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)