<a href="https://colab.research.google.com/github/Burkifa23/kwizeramugwaneza_frank_lab0/blob/master/colab_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 1 NumPy Fundamentals

**Creating Arrays**


In [17]:
import numpy as np

# Creating arrays
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.zeros((3, 4))          # 3x4 array of zeros
arr3 = np.ones((2, 3))           # 2x3 array of ones
arr4 = np.random.randn(3, 3)     # 3x3 random normal
arr5 = np.arange(0, 10, 2)       # [0, 2, 4, 6, 8]
arr6 = np.linspace(0, 1, 5)      # 5 evenly spaced values

print(f"Shape of arr2: {arr2.shape}\n")
print(f"Dimensions: {arr2.ndim}\n")
print(f"Data type: {arr3.dtype}\n")

Shape of arr2: (3, 4)

Dimensions: 2

Data type: float64



**Array Indexing and Slicing**

In [18]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

print(f"First element: {arr[0, 0]}\n")
print(f"Second column: {arr[:, 1]}\n")
print(f"Rows 1-2, cols 2-3: \n{arr[1:3, 2:4]}\n")
print(f"Boolean indexing: {arr[arr > 5]}")

First element: 1

Second column: [ 2  6 10]

Rows 1-2, cols 2-3: 
[[ 7  8]
 [11 12]]

Boolean indexing: [ 6  7  8  9 10 11 12]


**Broadcasting**

Broadcasting allows operations between arrays of different shapes:


In [19]:
# Broadcasting example
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
vector = np.array([10, 20, 30])

# Broadcasting adds vector to each row
result = matrix + vector
print(result)
# [[11, 22, 33],
#  [14, 25, 36],
#  [17, 28, 39]]

# Normalization using broadcasting
data = np.random.randn(100, 5)
print(f"Original Data: \n{data[:5]}\n")
normalized = (data - data.mean(axis=0)) / data.std(axis=0)
print(f"Normalized Data: \n{normalized[:5]}")

[[11 22 33]
 [14 25 36]
 [17 28 39]]
Original Data: 
[[-1.54320076  2.17774402 -0.27351568  1.3812758   0.6628211 ]
 [ 1.1552231   0.34409388  0.73490361  0.24973054  0.36315692]
 [-1.70704231  0.90547117  1.05369098 -2.23008157 -1.22017107]
 [ 0.90445891  0.51345705  2.63955893  0.43664044 -0.09392094]
 [ 1.16709491  0.29051805  1.19837004 -0.67112097 -0.64333157]]

Normalized Data: 
[[-1.87326036  2.01543955 -0.29775272  1.42869953  0.79252684]
 [ 1.11732779  0.29729199  0.70651251  0.28279852  0.49375922]
 [-2.0548414   0.82330784  1.02398668 -2.22847458 -1.08483166]
 [ 0.83941282  0.45598688  2.60332183  0.47207973  0.03804888]
 [ 1.130485    0.24709093  1.16806975 -0.64973569 -0.50971798]]


**Matrix Operations**


In [20]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Matrix multiplication
C = A @ B  # or np.matmul(A, B)
print(f"Product AB: \n{C}\n")

# Element-wise multiplication
D = A * B
print(f"Element-wise multiplication: \n{D}\n")


# Transpose
A_T = A.T
print(f"Transpose of A: \n{A_T}\n")

# Inverse (requires square, non-singular matrix)
A_inv = np.linalg.inv(A)
print(f"Inverse of A: \n{A_inv}\n")

# Determinant
det_A = np.linalg.det(A)
print(f"Determinant of A: {det_A}\n")

# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

print(f"Eigenvalues: {eigenvalues}\n")
print(f"Eigenvectors: \n{eigenvectors}\n")

Product AB: 
[[19 22]
 [43 50]]

Element-wise multiplication: 
[[ 5 12]
 [21 32]]

Transpose of A: 
[[1 3]
 [2 4]]

Inverse of A: 
[[-2.   1. ]
 [ 1.5 -0.5]]

Determinant of A: -2.0000000000000004

Eigenvalues: [-0.37228132  5.37228132]

Eigenvectors: 
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]



### 2 Pandas Fundamentals

Pandas provides powerful data structures for data manipulation and analysis.

**DataFrames and Series**

In [24]:
import pandas as pd

# Creating a DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana'],
    'Age': [25, 30, 35, 28],
    'Score': [85.5, 92.0, 78.5, 95.5]
}
df = pd.DataFrame(data)

# Creating a Series
scores = pd.Series([85.5, 92.0, 78.5, 95.5], name='Score')

# Basic DataFrame operations
print(f"First 2 rows: \n{df.head(2)}\n")
print(f"Data types and memory usage: \n{df.info()}\n")
print(f"Statistical summary: \n{df.describe()}\n")
print(f"rows, columns: {df.shape}\n")


First 2 rows: 
    Name  Age  Score
0  Alice   25   85.5
1    Bob   30   92.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    4 non-null      object 
 1   Age     4 non-null      int64  
 2   Score   4 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 228.0+ bytes
Data types and memory usage: 
None

Statistical summary: 
             Age      Score
count   4.000000   4.000000
mean   29.500000  87.875000
std     4.203173   7.498611
min    25.000000  78.500000
25%    27.250000  83.750000
50%    29.000000  88.750000
75%    31.250000  92.875000
max    35.000000  95.500000

rows, columns: (4, 3)




**Data Loading and Inspection**

In [27]:
import kagglehub
import pandas as pd

path = kagglehub.dataset_download("gregorut/videogamesales")

# Reading CSV files
vg = pd.read_csv(f'{path}/vgsales.csv')

# Reading Excel files
# df = pd.read_excel('data.xlsx', sheet_name='Sheet1')

# Quick inspection
vg.head(10)          # First 10 rows
vg.tail(5)           # Last 5 rows
vg.columns           # Column names
vg.dtypes            # Data types
vg.isnull().sum()    # Count missing values

Using Colab cache for faster access to the 'videogamesales' dataset.


,0
Rank,0
Name,0
Platform,0
Year,271
Genre,0
Publisher,58
NA_Sales,0
EU_Sales,0
JP_Sales,0
Other_Sales,0


**Data Manipulation**

In [28]:
# Filtering
high_scorers = df[df['Score'] > 90]
print(f"Filtering \n{high_scorers}\n")

# Multiple conditions
selected = df[(df['Age'] > 25) & (df['Score'] > 80)]
print(f"Multiple conditions \n{selected}\n")

# Adding new columns
df['Passed'] = df['Score'] >= 80
print(f"Adding new columns \n{df}\n")

# Grouping and aggregation
gr_agg=df.groupby('Age')['Score'].agg(['mean', 'std', 'count'])
print(f"Grouping and aggregation: \n{gr_agg}\n")

# Sorting
df_sorted = df.sort_values('Score', ascending=False)
print(f"Sorting: \n{df_sorted}\n")

# Handling missing values
df_clean = df.dropna()
print(f"Handling missing values: \n{df_clean}\n")
df_filled = df.fillna(df.mean(numeric_only=True))
print(f"Handling missing values: \n{df_filled}\n")

Filtering 
    Name  Age  Score
1    Bob   30   92.0
3  Diana   28   95.5

Multiple conditions 
    Name  Age  Score
1    Bob   30   92.0
3  Diana   28   95.5

Adding new columns 
      Name  Age  Score  Passed
0    Alice   25   85.5    True
1      Bob   30   92.0    True
2  Charlie   35   78.5   False
3    Diana   28   95.5    True

Grouping and aggregation: 
     mean  std  count
Age                  
25   85.5  NaN      1
28   95.5  NaN      1
30   92.0  NaN      1
35   78.5  NaN      1

Sorting: 
      Name  Age  Score  Passed
3    Diana   28   95.5    True
1      Bob   30   92.0    True
0    Alice   25   85.5    True
2  Charlie   35   78.5   False

Handling missing values: 
      Name  Age  Score  Passed
0    Alice   25   85.5    True
1      Bob   30   92.0    True
2  Charlie   35   78.5   False
3    Diana   28   95.5    True

Handling missing values: 
      Name  Age  Score  Passed
0    Alice   25   85.5    True
1      Bob   30   92.0    True
2  Charlie   35   78.5   False
3    D

**Merging and Joining**


In [29]:
df1 = pd.DataFrame({'ID': [1, 2, 3], 'Name': ['A', 'B', 'C']})
df2 = pd.DataFrame({'ID': [1, 2, 4], 'Score': [90, 85, 88]})

# Inner join
inner = pd.merge(df1, df2, on='ID', how='inner')
print(f"Inner join: \n{inner}\n")
# Left join
left = pd.merge(df1, df2, on='ID', how='left')
print(f"Left join: \n{left}\n")

# Right join
right = pd.merge(df1, df2, on='ID', how='right')
print(f"Right join: \n{right}\n")


Inner join: 
   ID Name  Score
0   1    A     90
1   2    B     85

Left join: 
   ID Name  Score
0   1    A   90.0
1   2    B   85.0
2   3    C    NaN

Right join: 
   ID Name  Score
0   1    A     90
1   2    B     85
2   4  NaN     88

