<a href="https://colab.research.google.com/github/Burkifa23/kwizeramugwaneza_frank_lab0/blob/master/colab_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1 NumPy Fundamentals
**Creating Arrays**


In [1]:
import numpy as np

# Creating arrays
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.zeros((3, 4))          # 3x4 array of zeros
arr3 = np.ones((2, 3))           # 2x3 array of ones
arr4 = np.random.randn(3, 3)     # 3x3 random normal
arr5 = np.arange(0, 10, 2)       # [0, 2, 4, 6, 8]
arr6 = np.linspace(0, 1, 5)      # 5 evenly spaced values

print(f"Shape of arr2: {arr2.shape}")
print(f"Dimensions: {arr2.ndim}")
print(f"Data type: {arr3.dtype}")

Shape of arr2: (3, 4)
Dimensions: 2
Data type: float64


**Array Indexing and Slicing**

In [2]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

print(f"First element: {arr[0, 0]}")
print(f"Second column: {arr[:, 1]}")
print(f"Rows 1-2, cols 2-3: \n{arr[1:3, 2:4]}")
print(f"Boolean indexing: {arr[arr > 5]}")

First element: 1
Second column: [ 2  6 10]
Rows 1-2, cols 2-3: 
[[ 7  8]
 [11 12]]
Boolean indexing: [ 6  7  8  9 10 11 12]


**Broadcasting**

Broadcasting allows operations between arrays of different shapes:


In [8]:
# Broadcasting example
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
vector = np.array([10, 20, 30])

# Broadcasting adds vector to each row
result = matrix + vector
print(result)
# [[11, 22, 33],
#  [14, 25, 36],
#  [17, 28, 39]]

# Normalization using broadcasting
data = np.random.randn(100, 5)
print(f"Original Data: \n{data[:5]}")
normalized = (data - data.mean(axis=0)) / data.std(axis=0)
print(f"Normalized Data: \n{normalized[:5]}")

[[11 22 33]
 [14 25 36]
 [17 28 39]]
Original Data: 
[[-0.55859765 -0.47946477  0.15042772 -0.86732238 -1.12850491]
 [-0.47222136  0.0915829  -0.55049253  1.25237982  0.32658097]
 [-0.45177332  1.00375598  1.5757344  -0.13680267  2.09614569]
 [ 1.50883701 -1.31704741 -0.01419592  1.57283766 -1.07047326]
 [ 1.20824544  1.74116984 -1.22347447 -1.06068373 -0.48656995]]
Normalized Data: 
[[-0.57672384 -0.57560763  0.13292561 -0.99219283 -1.02745749]
 [-0.48583113  0.01486519 -0.56379232  1.09458167  0.29726954]
 [-0.4643139   0.95806737  1.54968695 -0.2730211   1.90830174]
 [ 1.59881231 -1.44168203 -0.03071104  1.41006148 -0.97462481]
 [ 1.28250349  1.72056559 -1.23273944 -1.18255047 -0.44303248]]


**Matrix Operations**


In [10]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Matrix multiplication
C = A @ B  # or np.matmul(A, B)
print(f"Product AB: \n{C}")

# Element-wise multiplication
D = A * B
print(f"Element-wise multiplication: \n{D}")


# Transpose
A_T = A.T
print(f"Transpose of A: \n{A_T}")

# Inverse (requires square, non-singular matrix)
A_inv = np.linalg.inv(A)
print(f"Inverse of A: \n{A_inv}")

# Determinant
det_A = np.linalg.det(A)
print(f"Determinant of A: {det_A}")

# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

print(f"Eigenvalues: {eigenvalues}")
print(f"Eigenvectors: \n{eigenvectors}")

Product AB: 
[[19 22]
 [43 50]]
Element-wise multiplication: 
[[ 5 12]
 [21 32]]
Transpose of A: 
[[1 3]
 [2 4]]
Inverse of A: 
[[-2.   1. ]
 [ 1.5 -0.5]]
Determinant of A: -2.0000000000000004
Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors: 
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
